# Generated by Django 4.1.5 on 2023-02-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
